### ISSUE TITLE
HTTPFile provider

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulajs-configuration-service#19]
#### List of core packages that if affects
List all the core packages that this changes will affect.

#### Prerequisites
Links to any external dependency for this feature

## API
https://github.com/capsulajs/configuration-service/blob/develop/src/api/ConfigurationService.ts

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.
https://github.com/capsulajs/configuration-service/tree/develop/tests/features

## Ready for implementation
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Documentation
- [x] Release notes

## RoadMap

In case there is more than one mergeable point you can specify it here.
