### ISSUE TITLE
Expose multiple providers from Configuration service

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulajs-configuration-service#21]
## General description
Configuration Service should expose a function that will return an appropriate Configuration Provider based on configurationType.
Allow to use not only http protocol, but also https (include the protocol inside the token).

#### Changes

https://github.com/capsulajs/configuration-service/pull/22

## Behavior

- [x] Does the suggested changes impact the current behaviour ?
The recommended way to get a Configuration Provider is to use this function with specifying the required configurationType.
- [ ] Does the suggested changes are specific to some devices/browsers/environments
- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases

https://github.com/capsulajs/configuration-service/pull/23

## Ready for implementation
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [x] Release notes

## RoadMap

In case there is more than one mergeable point you can specify it here.
